// Frontend/skillforge-svelte/src/components/user-list-item/UserListItem.svelte
<script lang="ts">
	import FollowButton from "$components/follow-button/FollowButton.svelte";
	import UserLink from "$components/user-link/UserLink.svelte";
	import { currentUserStore } from "$lib/stores/currentUserStore";
	import type UserListItemType from "$lib/types/UserListItemType";

    interface Props {
        data: UserListItemType,
        mod?: string
    }

    let {
        data,
        mod
    }: Props = $props();
</script>

<div class="d-flex justify-content-center justify-content-lg-between align-items-center {mod}">
    <UserLink data={data.Link} />
    {#if $currentUserStore && $currentUserStore.Name != data.Link.Name}
        <FollowButton
            subjectName={data.Link.Name}
            type="user"
            isFollowedByCurrentUser={data.IsFollowedByCurrentUser}
            btnSize="sm"
        />
    {/if}
</div>

// Frontend/skillforge-react/src/components/user-list-item/UserListItem.tsx
'use client';

import { UserLink } from '../user-link/UserLink';
import { FollowButton } from '../follow-button/FollowButton';
import UserListItemType from '@/lib/types/UserListItemType';
import { useCurrentUser } from '@/hooks/useCurrentUser';

export interface IUserListItemProps {
    data: UserListItemType;
    classes?: string;
}

export function UserListItem({
    data,
    classes = ''
}: IUserListItemProps) {
    const { currentUser } = useCurrentUser();

    return (
        <div className={`d-flex justify-content-center justify-content-lg-between align-items-center ${classes}`}>
            <UserLink data={data.Link} />
            {(currentUser && currentUser.Name != data.Link.Name) &&
                <FollowButton
                    subjectName={data.Link.Name}
                    type="user"
                    isFollowedByCurrentUser={data.IsFollowedByCurrentUser}
                    btnSize="sm"
                />
            }
        </div>
    );
}
