// Frontend/skillforge-react/src/components/report-modal/ReportModal.tsx
import { Modal } from '../modal/Modal';
import { ModalHeader } from '../modal-header/ModalHeader';
import { Button } from '../button/Button';
import { Form } from '../form/Form';
import { RadioGroup } from '../form/radio-group/RadioGroup';
import { RadioField } from '../form/radio-field/RadioField';
import { useReportFormOptions } from '@/hooks/useReportFormOptions';
import { useState } from 'react';
import { useToast } from '@/hooks/useToast';
import ReportFormData from '@/lib/types/ReportFormData';
import { TextAreaField } from '../form/text-area-field/TextAreaField';

export interface IReportModalProps {
    title: string;
    entityId?: number;
    entityName?: string;
    action: string;
    show: boolean;
    setShow: (show: boolean) => void;
}

export function ReportModal({
    title,
    entityId,
    entityName,
    action,
    show,
    setShow,
}: IReportModalProps) {
    const { reportOptions } = useReportFormOptions();
    const { addToast } = useToast();

    const [reason, setReason] = useState<number>();
    const [message, setMessage] = useState<string>('');

    function onSubmit(data: ReportFormData) {
        data.Id = entityId;
        data.Name = entityName;

        return data;
    }

    function onSuccess() {
        addToast('Report submitted successfully.', 'success');
        setShow(false);
    }

    return (
        <Modal show={show} setShow={setShow} header={<ModalHeader title={title} />} verticallyCentered>
            {reportOptions &&
                <div className="px-4">
                    <Form action={action} onSubmit={onSubmit} onSuccess={onSuccess}>
                        <RadioGroup name="Reason">
                            {reportOptions?.ViolationOptions.map(o => (
                                <RadioField<number | undefined>
                                    id={`Reason-${o.Value}`}
                                    key={o.Value}
                                    name="Reason"
                                    value={o.Value}
                                    label={o.Label}
                                    classes="mb-3"
                                    selectedOption={reason}
                                    onChange={setReason}
                                />
                            ))}
                        </RadioGroup>

                        {reason == 7 &&
                            <TextAreaField
                                id="Message"
                                rows="4"
                                placeholder="Message..."
                                value={message}
                                onChange={setMessage}
                            />
                        }

                        <div className="text-center">
                            <Button classes="mt-3" isSubmitButton>Submit</Button>
                        </div>
                    </Form>
                </div>
            }
        </Modal>
    );
}

// Frontend/skillforge/src/components/report/ReportModal.svelte
<script lang="ts">
	import Form from '$components/form/Form.svelte';
	import TextAreaField from '$components/form/text-area-field/TextAreaField.svelte';
	import Modal from '$components/modal/Modal.svelte';
	import ModalHeader from '$components/modal-header/ModalHeader.svelte';
	import { addToast } from '$lib/stores/toastStore';
	import type ReportFormData from '$lib/types/ReportFormData';
	import { writable } from 'svelte/store';
	import RadioGroup from '$components/form/radio-group/RadioGroup.svelte';
	import RadioField from '$components/form/radio-field/RadioField.svelte';
	import Button from '$components/button/Button.svelte';
	import { reportFormOptionsStore } from '$lib/stores/reportFormOptionsStore';

	interface Props {
		entityId?: number;
		entityName?: string;
		action: string;
		show: boolean;
	}

	let {
		entityId,
		entityName,
		action,
		show = $bindable<boolean>()
	}: Props = $props();

	let formData = writable<ReportFormData>({
		Id: entityId,
		Name: entityName,
		Reason: 0
	});

	function onSuccess() {
		addToast('Report submitted successfully.', 'success');
		show = false;
	}
</script>

<Modal bind:show verticallyCentered>
	{#snippet header()}
		<ModalHeader title="Report article" />
	{/snippet}

	{#if $reportFormOptionsStore}
		<div class="px-4">
			<Form {action} formData={$formData} {onSuccess} resetMode="onsuccess">
				<RadioGroup name="Reason">
					{#each $reportFormOptionsStore.ViolationOptions as o}
						<RadioField
							id="Reason-{o.Value}"
							name="Reason"
							value={o.Value}
							label={o.Label}
							mod="mb-3"
							bind:group={$formData.Reason}
						/>
					{/each}
				</RadioGroup>

				{#if $formData.Reason === 8}
					<TextAreaField
						id="Message"
						rows="4"
						placeholder="Message..."
						bind:value={$formData.Message}
					/>
				{/if}

				<div class="text-center">
					<Button mod="mt-3" isSubmitButton>Submit</Button>
				</div>
			</Form>
		</div>
	{/if}
</Modal>
