// Frontend/skillforge-react/src/components/form/input-field/InputField.tsx
import { FormContext } from 'context/FormContext';
import { useContext } from 'react';
import type { FieldValues, RegisterOptions } from 'react-hook-form';
import type { InputType } from 'skillforge-common/types/InputType';

export interface IInputFieldProps {
    id: string;
    name?: string;
    label?: string;
    type?: InputType;
    value?: any;
    onChange?: (value: any) => void;
    options?: RegisterOptions<FieldValues, string> | undefined,
    placeholder?: string;
    min?: any;
    max?: any;
    minLength?: any;
    maxLength?: any;
    step?: any;
    classes?: string;
    disabled?: boolean;
}

export function InputField(props: IInputFieldProps) {
    const formContext = useContext(FormContext);

    const formClass = props.type === 'range' ? 'form-range' : 'form-control';
    const formName: string = props.name ?? props.id;

    return (
        <div className="mb-4">
            <label htmlFor={props.id} className="form-label">{props.label}:</label>
            <input
                    {...formContext?.form.register(formName, {
                        ...props.options,
                        onChange: e => props.onChange?.(e.target.value)
                    })}
                    id={props.id}
                    type={props.type}
                    placeholder={props.placeholder}
                    className={`
                        ${formClass}
                        ${props.classes ?? ''}
                        ${(!!formContext?.form.formState.errors[formName]) ? 'is-invalid' : ''}`}
                    value={props.value}
                    min={props.min}
                    max={props.max}
                    minLength={props.minLength}
                    maxLength={props.maxLength}
                    step={props.step}
                    disabled={props.disabled}
            />
            <div className="invalid-feedback">
                {formContext?.form.formState.errors[formName] && formContext?.form.formState.errors[formName]?.message as string}
            </div>
        </div>
    );
}

// Frontend/skillforge-svelte/src/components/form/input-field/InputField.svelte
<script lang="ts">
	import type ValidatedField from 'skillforge-common/types/ValidatedField';
	import type { InputType } from 'skillforge-common/types/InputType';
	import FieldValidation from '../field-validation/FieldValidation.svelte';
	import { getContext, onMount } from 'svelte';
	import type FormContext from 'skillforge-common/types/FormContext';

    interface Props {
        id: string,
        name?: string,
        label?: string,
        type?: InputType,
        value: any,
        placeholder?: string,
        min?: any,
        max?: any,
        minlength?: any,
        maxlength?: any,
        step?: any,
        mod?: string,
        disabled?: boolean,
        validateTogether?: string[],
    }

    var {
        id,
        name = id,
        label = name,
        type = 'text',
        value = $bindable(),
        placeholder,
        min,
        max,
        minlength,
        maxlength,
        step,
        mod,
        disabled,
        validateTogether,
    }: Props = $props();

    const formContext = getContext<FormContext>('form');

    let isValid = $state<boolean>(true);
    let isVisited = $state<boolean>(false);
    let formClass = $derived<string>(type === 'range' ? 'form-range' : 'form-control');

    let fieldValidation: ValidatedField;
    function oninput() {
        fieldValidation?.validate();
    }

    function onfocus() {
        isVisited = true;
    }

    function onfocusout() {
        fieldValidation?.validate();
    }

    export function reset() {
        value = formContext?.getFieldDefaultValue(name);
    }

    onMount(() => {
        formContext?.registerField(name, reset);
    })
</script>

<div class="mb-4">
    <label for={id} class="form-label">{label}:</label>
    <input {id}
            {type}
            {name}
            {placeholder}
            class="{formClass} {mod}"
            class:is-invalid={!isValid}
            bind:value
            {min}
            {max}
            {minlength}
            {maxlength}
            {step}
            {oninput}
            {onfocus}
            {onfocusout}
            {disabled}>
    <FieldValidation {name} {label} {value} shouldValidate={isVisited} bind:isValid bind:this={fieldValidation} {validateTogether} />
</div>
