// Frontend/skillforge/src/components/button/Button.svelte
<script lang="ts">
	import type { BootstrapColor } from "$lib/types/BootstrapColor";
	import type { BootstrapSize } from "$lib/types/BootstrapSize";
	import type FormContext from "$lib/types/FormContext";
	import { getContext, type Snippet } from "svelte";
	import type { MouseEventHandler } from "svelte/elements";

    interface Props {
        color?: BootstrapColor,
        size?: BootstrapSize,
        mod?: string,
        isOutline?: boolean,
        isSubmitButton?: boolean,
        disabled?: boolean,
        onclick?: MouseEventHandler<HTMLButtonElement>,
        children?: Snippet
    }

    let {
        color = 'primary',
        size,
        mod,
        isOutline,
        isSubmitButton,
        disabled,
        onclick,
        children
    }: Props = $props();

    let isLoading = $state<boolean>(false);
    let colorClass = $derived(`btn${isOutline ? '-outline' : ''}-${color}`)

    let formContext = getContext<FormContext>('form');

    async function onclickPrivate(event: MouseEvent & { currentTarget: EventTarget & HTMLButtonElement; }) {
        isLoading = true;

        if (isSubmitButton) {
            await formContext?.submit();
        }

        await onclick?.(event);

        isLoading = false;
    }
</script>

<button type="button" class="btn {colorClass} {mod} {size ? 'btn-' + size : ''}" class:disabled onclick={onclickPrivate} disabled={disabled || isLoading}>
    {#if isLoading}
        <span class="spinner-border spinner-border-sm" aria-hidden="true"></span>
        <span role="status">Processing...</span>
    {:else}
        {@render children?.()}
    {/if}
</button>

// Frontend/skillforge-react/src/components/button/Button.tsx
'use client'

import { FormContext } from '../../context/FormContext';
import React, { useContext, useState, type MouseEvent, type MouseEventHandler } from 'react';
import type { BootstrapColor } from "@/lib/types/BootstrapColor";
import type { BootstrapSize } from "@/lib/types/BootstrapSize";

export interface IButtonProps {
    color?: BootstrapColor;
    size?: BootstrapSize;
    classes?: string;
    isOutline?: boolean;
    isSubmitButton?: boolean;
    disabled?: boolean;
    onClick?: MouseEventHandler<HTMLButtonElement>;
    children?: React.ReactNode;
}

export function Button(props: IButtonProps) {

    const [isLoading, setIsLoading] = useState<boolean>(false);
    const colorClass = `btn${props.isOutline ? '-outline' : ''}-${props.color ?? 'primary'}`;

    let formContext = useContext(FormContext);

    async function onClickPrivate(event: MouseEvent<HTMLButtonElement>) {
        setIsLoading(true);

        if (props.isSubmitButton) {
            await formContext?.submit();
        }

        props.onClick?.(event);

        setIsLoading(false);
    }

    return (
        <button type="button"
            className={`btn ${colorClass} ${props.classes ?? ''} ${props.size ? 'btn-' + props.size : ''} ${props.disabled ? 'disabled' : ''}`}
            onClick={onClickPrivate}
            disabled={props.disabled || isLoading}>
            {isLoading ?
                <span>
                    <span className="spinner-border spinner-border-sm" aria-hidden="true"></span>
                    <span role="status">Processing...</span>
                </span>
                :
                <span>{props.children}</span>
            }
        </button>
    );
}
