// Frontend/skillforge-svelte/src/routes/article/[id]/+page.svelte
<script lang="ts">
	import AnchorList from '$components/anchor-list/AnchorList.svelte';
	import Article from '$components/article/Article.svelte';
	import TopArticleLink from '$components/top-article-link/TopArticleLink.svelte';
	import TwoColumns from '$components/layout/TwoColumns.svelte';
	import AuthorBlock from '$components/author-block/AuthorBlock.svelte';
	import { PUBLIC_BASE_URL } from '$env/static/public';
	import { generateUserLinkSchema } from '$lib/structuredDataUtil';
	import type ArticlePageModel from 'skillforge-common/types/ArticlePageModel';
	import { getFrontendUrl, getImagePath, htmlToText, truncateText } from '$lib/util';

	interface Props {
		data: ArticlePageModel;
	}

	let { data }: Props = $props();
</script>

<svelte:head>
	<title>SkillForge | {data.Title}</title>
	<meta
		name="description"
		content="{truncateText(htmlToText(data.Content), 120)} Tags: {data.Tags.join(', ')}"
	/>
	<meta name="robots" content="index,follow" />
	<link rel="canonical" href="{PUBLIC_BASE_URL}/article/{data.ArticleId}" />
</svelte:head>

<TwoColumns>
	{#snippet leftColumn()}
		<AuthorBlock data={data.Author} mod="mb-4" />

		{#if data.LatestArticlesByAuthor.length > 0}
			<AnchorList title="Latest by author" items={data.LatestArticlesByAuthor}>
				{#snippet itemSnippet(item)}
					<TopArticleLink data={item} />
				{/snippet}
			</AnchorList>
		{/if}
	{/snippet}

	<Article {data} />
</TwoColumns>

{@html `<script type="application/ld+json">
	${JSON.stringify({
		'@context': 'https://schema.org',
		'@type': 'Article',
		author: generateUserLinkSchema(data.Author.Link),
		mainEntityOfPage: getFrontendUrl('/article/' + data.ArticleId),
		articleBody: truncateText(htmlToText(data.Content), 400),
		datePublished: data.DatePublished,
		headline: data.Title,
		image: data.CoverImage ? getImagePath(data.CoverImage) : '',
		keywords: data.Tags.join(','),
		commentCount: data.Comments.length,
		comments: data.Comments.map((c) => {
			return {
				'@type': 'Comment',
				author: generateUserLinkSchema(c.User),
				text: truncateText(htmlToText(c.Content), 80),
				upvoteCount: c.RatingData.ThumbsUp,
				downvoteCount: c.RatingData.ThumbsDown,
				datePublished: c.DateWritten
			};
		})
	})}
</script>`}

// Frontend/skillforge-react/src/app/article/[id]/page.tsx
import { AnchorList } from "@/components/anchor-list/AnchorList";
import { Article } from "@/components/article/Article";
import { AuthorBlock } from "@/components/author-block/AuthorBlock";
import { TwoColumns } from "@/components/layout/two-columns/TwoColumns";
import { TopArticleLink } from "@/components/top-article-link/TopArticleLink";
import { GetServerSidePropsContext, Metadata } from "next";
import { viewArticle } from "skillforge-common/api/client";
import type ArticlePageModel from 'skillforge-common/types/ArticlePageModel';
import { getFrontendUrl, htmlToText, truncateText } from "skillforge-common/util";

export async function generateMetadata({ params }: GetServerSidePropsContext): Promise<Metadata> {
    const data: ArticlePageModel = await viewArticle(parseInt(params?.id as string));

    return {
        title: `SkillForge | ${data.Title}`,
        description: `${truncateText(htmlToText(data.Content), 120)}, Tags: ${data.Tags.join(', ')}`,
        robots: 'index,follow',
        alternates: {
            canonical: getFrontendUrl(`/article/${params?.id}`)
        }
    };
}

export default async function ArticleView({ params }: GetServerSidePropsContext) {
    const data: ArticlePageModel = await viewArticle(parseInt(params?.id as string));

    function leftColumn() {
        return (
            <>
                <AuthorBlock data={data.Author} classes="mb-4" />

                {data.LatestArticlesByAuthor.length > 0 &&
                    <AnchorList
                        title="Latest by author"
                        items={data.LatestArticlesByAuthor}
                        itemSnippet={item => <TopArticleLink data={item} key={`top-article-${item.ArticleId}`} />}
                    />
                }
            </>
        );
    }

    return (
        <TwoColumns leftColumn={leftColumn()}>
            <Article data={data} />
        </TwoColumns>
    );
}
