// Frontend/skillforge-react/src/components/login-form/LoginForm.tsx
import { useState } from 'react';
import type LoginResponse from 'skillforge-common/types/LoginResponse';
import { storeAuthToken } from 'skillforge-common/auth';
import { useNavigate } from 'react-router-dom';
import { useCurrentUser } from 'hooks/useCurrentUser';
import { Form } from '@components/form/Form';
import { InputField } from '@components/form/input-field/InputField';
import { Button } from '@components/button/Button';

export function LoginForm() {
    const { setCurrentUser } = useCurrentUser();
    const navigate = useNavigate();

    const [usernameOrEmail, setUsernameOrEmail] = useState<string>('');
    const [password, setPassword] = useState<string>('');

    async function onSuccess(response: LoginResponse) {
        setCurrentUser(response.CurrentUserInfo);
        storeAuthToken(response.AuthToken);

        // addToast('Successfully logged in');

        navigate('/user/' + response.CurrentUserInfo.Name);
    }

    return (
        <section className="mb-5">
            <h2>Sign in</h2>
            <Form
                action="/User/Auth"
                method="POST"
                onSuccess={onSuccess}
            >
                <div className="row">
                    <div className="col-12">
                        <InputField
                            id="UsernameOrEmail"
                            type="text"
                            label="Username or e-mail"
                            value={usernameOrEmail}
                            onChange={setUsernameOrEmail}
                            options={{
                                required: 'Please enter a valid username or e-mail address.'
                            }}
                        />
                    </div>
                    <div className="col-12">
                        <InputField
                            id="Password"
                            type="password"
                            label="Password"
                            value={password}
                            onChange={setPassword}
                            options={{
                                required: 'Please enter your password.'
                            }}
                        />
                    </div>
                </div>

                <div className="text-center text-lg-start">
                    <Button size="lg" isSubmitButton={true}>Sign in</Button>
                </div>
            </Form>
        </section>
    );
}

// Frontend/skillforge-svelte/src/components/login-form/LoginForm.svelte
<script lang="ts">
	import Form from '../form/Form.svelte';
	import InputField from '../form/input-field/InputField.svelte';
	import type ValidationRules from 'skillforge-common/types/ValidationRules';
	import { required } from 'skillforge-common/validation/rules';
	import type UserLoginCredentials from 'skillforge-common/types/UserLoginCredentials';
	import { writable } from 'svelte/store';
	import Button from '../button/Button.svelte';
	import type UserInfo from 'skillforge-common/types/UserInfo';
	import { currentUserStore } from '$lib/stores/currentUserStore';
	import { goto, invalidate } from '$app/navigation';
	import { addToast } from '$lib/stores/toastStore';
	import type LoginResponse from 'skillforge-common/types/LoginResponse';
	import { storeAuthToken } from '$lib/auth';

	let formData = writable<UserLoginCredentials>({
		UsernameOrEmail: '',
		Password: ''
	});

	let validationRules: ValidationRules = {
		UsernameOrEmail: [
			{
				validate: required,
				message: () => `Please enter a valid username or e-mail address.`
			}
		],
		Password: [
			{
				validate: required,
				message: () => `Please enter your password.`
			}
		]
	};

	async function onLoginSuccess(response: LoginResponse) {
		currentUserStore.set(response.CurrentUserInfo);
		storeAuthToken(response.AuthToken);
		await invalidate('app:auth');

		addToast('Successfully logged in');

		goto('/user/' + response.CurrentUserInfo.Name);
	}
</script>

<section class="mb-5">
	<h2>Sign in</h2>
	<Form
		action="/User/Auth"
		method="POST"
		formData={$formData}
		onSuccess={onLoginSuccess}
		{validationRules}
		resetMode="onsubmit"
	>
		<div class="row">
			<div class="col-12">
				<InputField
					id="UsernameOrEmail"
					type="text"
					label="Username or e-mail"
					bind:value={$formData.UsernameOrEmail}
				/>
			</div>
			<div class="col-12">
				<InputField
					id="Password"
					type="password"
					label="Password"
					bind:value={$formData.Password}
				/>
			</div>
		</div>

        <div class="text-center text-lg-start">
		    <Button size="lg" isSubmitButton={true}>Sign in</Button>
        </div>
	</Form>
</section>
