// Frontend/skillforge-react/src/components/comment-limited/CommentLimited.tsx
import { AuthorBox } from '@/components/author-box/AuthorBox';
import type CommentModel from '@/lib/types/CommentModel';

export interface ICommentLimitedProps {
    data: CommentModel
}

export function CommentLimited({ data }: ICommentLimitedProps) {
    return (
        <>
            <AuthorBox
                name={data.User.Name}
                avatarImage={data.User.AvatarImage}
                date={data.DateWritten}
                editedDate={data.DateEdited}
                size="small"
            />
            <div className="mx-5 p-3">
                <div className="content-wrapper rounded-3 p-3">
                    <div className="content text-break rich-text-content" dangerouslySetInnerHTML={{ __html: data.Content }}></div>
                </div>
            </div>
        </>
    );
}

// Frontend/skillforge/src/components/comment/CommentLimited.svelte
<script lang="ts">
	import AuthorBox from '$components/user/AuthorBox.svelte';
	import type CommentModel from '$lib/types/CommentModel';

	interface Props {
		data: CommentModel;
	}

	let { data }: Props = $props();
</script>

<AuthorBox
	name={data.User.Name}
	avatarImage={data.User.AvatarImage}
	date={data.DateWritten}
	editedDate={data.DateEdited}
	size="small"
/>
<div class="mx-5 p-3">
	<div class="content-wrapper rounded-3 p-3">
		<div class="content text-break rich-text-content">
			{@html data.Content}
		</div>
	</div>
</div>

<style lang="scss">
	.content {
		line-clamp: 2;
		-webkit-line-clamp: 2;
		display: -webkit-box;
		-webkit-box-orient: vertical;
		overflow: hidden;

		&-wrapper {
			background-color: rgba(111, 66, 193, 50%);
		}
	}
</style>
