// Frontend/skillforge/src/components/dropdown/DropdownItem.svelte
<script lang="ts">
	import type { Snippet } from "svelte";
	import type { MouseEventHandler } from "svelte/elements";

    interface Props {
        href?: string,
        type?: 'link' | 'button' | 'text',
        onclick?: MouseEventHandler<HTMLButtonElement>,
        active?: boolean,
        disabled?: boolean,
        children: Snippet
    }

    const {
        href,
        type = 'link',
        active,
        disabled,
        onclick,
        children
    }: Props = $props();
</script>

<li>
    {#if type === 'button'}
        <button class="dropdown-item" class:active class:disabled {onclick}>
            {@render children()}
        </button>
    {:else if type === 'link'}
        <a class="dropdown-item" class:active class:disabled {href}>
            {@render children()}
        </a>
    {:else if type === 'text'}
        <span class="dropdown-item-text">
            {@render children()}
        </span>
    {/if}
</li>

// Frontend/skillforge-react/src/components/dropdown-item/DropdownItem.tsx
import * as React from 'react';
import Link from 'next/link';

export interface IDropdownItemProps {
    href?: string;
    type?: 'link' | 'button' | 'text';
    onClick?: React.MouseEventHandler<HTMLButtonElement>;
    active?: boolean;
    disabled?: boolean;
    children: React.ReactNode;
}

export function DropdownItem({
    href,
    type = 'link',
    onClick,
    active,
    disabled,
    children
}: IDropdownItemProps) {
    return (
        <li>
            {type === 'button' ? (
                <button onClick={onClick} className={`dropdown-item ${active ? 'active' : ''} ${disabled ? 'disabled' : ''}`}>
                    {children}
                </button>
            ) : type === 'link' ? (
                <Link href={href ?? ''} className={`dropdown-item ${active ? 'active' : ''} ${disabled ? 'disabled' : ''}`}>
                    {children}
                </Link>
            ) : type === 'text' ? (
                <span className="dropdown-item-text">
                    {children}
                </span>
            ) : ''}
        </li>
    );
}
