// Frontend/skillforge/src/components/infinite-scroll/InfiniteScroll.svelte
<script lang="ts" generics="T">
	import type { GutterLevel } from '$lib/types/GutterLevel';
	import type ScrollableStore from '$lib/types/ScrollableStore';
	import { getContext, onDestroy, onMount, type Snippet } from 'svelte';

	interface Props {
		mod?: string;
		batchSize: number;
		autoLoadOnMount?: boolean;
		preloadedBatches?: [T[]];
		listDirection?: 'row' | 'column',
		gap?: GutterLevel,
		loadMore: (batchIndex: number) => Promise<T[]>;
		itemSnippet: Snippet<[T]>;
		placeholderSnippet?: Snippet;
		outOfItemsSnippet?: Snippet;
	}

	let {
		mod,
		batchSize,
		autoLoadOnMount,
		preloadedBatches,
		listDirection = 'column',
		gap = 3,
		loadMore,
		itemSnippet,
		placeholderSnippet,
		outOfItemsSnippet
	}: Props = $props();

	let items = $state<T[]>(preloadedBatches?.flat() ?? []);
	let batchIndex = $state<number>(preloadedBatches?.length ?? 0);
	let outOfItems = $state<boolean>(false);
	let containerElement: HTMLElement;
	let isLoading = $state<boolean>(false);

	const scrollable = getContext<ScrollableStore>('scrollable');

	function getScrollableHeight() {
		if (
			scrollable &&
			typeof scrollable.getClientHeight !== 'undefined' &&
			scrollable.getClientHeight != null
		) {
			return scrollable.getClientHeight();
		}

		return document.documentElement.clientHeight;
	}

	function updateItemList(newItems: T[]) {
		items = items.concat(newItems);

		if (newItems.length < batchSize) {
			outOfItems = true;
		}

		batchIndex++;
	}

	async function loadMoreAndUpdateItemList() {
		if (isLoading) {
			return;
		}

		isLoading = true;

		let newItems = await loadMore(batchIndex);
		updateItemList(newItems);

		isLoading = false;
	}

	async function onScroll() {
		if (outOfItems) {
			return;
		}

		if (containerElement.getBoundingClientRect().bottom <= getScrollableHeight()) {
			await loadMoreAndUpdateItemList();
		}
	}

	onMount(async () => {
		if (scrollable?.onScroll) {
			scrollable.onScroll(onScroll);
		} else {
			window.addEventListener('scroll', onScroll);
		}

		if (autoLoadOnMount) {
			await loadMoreAndUpdateItemList();
		}
	});

	onDestroy(() => {
		if (typeof window !== 'undefined') {
			window.removeEventListener('scroll', onScroll);
		}
	});
</script>

<div bind:this={containerElement} class="d-flex flex-{listDirection} gap-{gap} {mod}">
	{#each items as item}
		{@render itemSnippet(item)}
	{/each}
	{#if outOfItems}
		{@render outOfItemsSnippet?.()}
	{/if}
	{#if isLoading}
		{@render placeholderSnippet?.()}
	{/if}
</div>

// Frontend/skillforge-react/src/components/infinite-scroll/InfiniteScroll.tsx
'use client'

import { useScrollableContext } from "@/context/ScrollableContext";
import { GutterLevel } from "@/lib/types/GutterLevel";
import { ReactNode, useEffect, useRef, useState } from "react";

export interface IInfiniteScrollProps<T> {
    classes?: string;
    batchSize: number;
    autoLoadOnMount?: boolean;
    preloadedBatches?: [T[]];
    listDirection?: 'row' | 'column',
    gap?: GutterLevel,
    loadMore: (batchIndex: number) => Promise<T[]>;
    itemSnippet: (item: T) => ReactNode;
    placeholderSnippet?: ReactNode;
    outOfItemsSnippet?: ReactNode;
}

export function InfiniteScroll<T>({
    classes,
    batchSize,
    autoLoadOnMount,
    preloadedBatches,
    listDirection = 'column',
    gap = 3,
    loadMore,
    itemSnippet,
    placeholderSnippet,
    outOfItemsSnippet
}: IInfiniteScrollProps<T>) {

    const [items, setItems] = useState<T[]>(preloadedBatches?.flat() ?? []);
    const [batchIndex, setBatchIndex] = useState<number>(preloadedBatches?.length ?? 0);
    const [outOfItems, setOutOfItems] = useState<boolean>(false);
    const containerElement = useRef<HTMLDivElement>(null);
    const [isLoading, setIsLoading] = useState<boolean>(false);

    const scrollable = useScrollableContext();

    function getScrollableHeight() {
        if (
            scrollable &&
            typeof scrollable.getClientHeight !== 'undefined' &&
            scrollable.getClientHeight != null
        ) {
            return scrollable.getClientHeight();
        }

        return document.documentElement.clientHeight;
    }

    function updateItemList(newItems: T[]) {
        setItems(items.concat(newItems));

        if (newItems.length < batchSize) {
            setOutOfItems(true);
        }

        setBatchIndex(batchIndex + 1);
    }

    async function loadMoreAndUpdateItemList() {
        if (isLoading) {
            return;
        }

        setIsLoading(true);

        let newItems = await loadMore(batchIndex);
        updateItemList(newItems);

        setIsLoading(false);
    }

    async function onScroll() {
        if (outOfItems) {
            return;
        }

        if (containerElement?.current && containerElement.current.getBoundingClientRect().bottom <= getScrollableHeight()) {
            await loadMoreAndUpdateItemList();
        }
    }

    useEffect(() => {
        if (scrollable?.onScroll) {
            scrollable.onScroll(onScroll);
        } else {
            window.addEventListener('scroll', onScroll);
        }

        if (autoLoadOnMount) {
            loadMoreAndUpdateItemList();
        }

        return () => {
            if (typeof window !== 'undefined') {
                window.removeEventListener('scroll', onScroll);
            }
        };
    }, []);

    return (
        <div ref={containerElement} className={`d-flex flex-${listDirection} gap-${gap} ${classes}`}>
            {items.map(itemSnippet)}
            {outOfItems && outOfItemsSnippet}
            {isLoading && placeholderSnippet}
        </div>
    );
}
