// Frontend/skillforge-svelte/src/components/grid/filters/search-bar/SearchBar.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { searchArticles } from '$lib/api/client';
	import type ArticleSearchItemType from '$lib/types/ArticleSearchItemType';
	import type GridContext from '$lib/types/GridContext';
	import moment from 'moment';
	import { getContext } from 'svelte';
	import { fade } from 'svelte/transition';

	interface Props {
		mod?: string;
	}

	let {
		mod,
	}: Props = $props();

	let inputValue = $state('');

	let gridContext = getContext<GridContext>('grid_context');

	function search() {
        gridContext.updateState('q', inputValue);
	}

	function onkeydown(e: KeyboardEvent & { currentTarget: EventTarget & HTMLInputElement }) {
		if (e.code === 'Enter') {
			if (inputValue.length) {
				search();
			}
		}
	}
</script>

<div class="input-group">
    <input
        id="search"
        type="search"
        class="form-control rounded-start-3"
        placeholder="Search articles..."
        aria-label="Search articles..."
        aria-describedby="search_button"
        autocomplete="off"
        {onkeydown}
        bind:value={inputValue}
    />
    <button class="btn btn-light rounded-end-3" type="button" id="search_button" onclick={search} disabled={!inputValue}>Search</button>
</div>

// Frontend/skillforge-react/src/components/grid/filters/search-bar/SearchBar.tsx
import GridState from "@/lib/types/GridState";

export interface ISearchBarProps {
    gridState: GridState;
}

export function SearchBar({
    gridState
}: ISearchBarProps) {
    return (
        <form method="GET">
            <div className="input-group">
                <input
                    id="search"
                    name="q"
                    type="search"
                    className="form-control rounded-start-3"
                    placeholder="Search articles..."
                    aria-label="Search articles..."
                    aria-describedby="search_button"
                    autoComplete="off"
                />
                <button className="btn btn-light rounded-end-3" type="submit" id="search_button">Search</button>
            </div>
            {gridState.sortBy && <input type="hidden" name="sortBy" value={gridState.sortBy} />}
            {gridState.sortOrder && <input type="hidden" name="sortOrder" value={gridState.sortOrder} />}
        </form>
    );
}
