// Frontend/skillforge/src/components/navbar/NavLink.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	interface Props {
		href: string;
		active?: boolean;
		children: Snippet;
	}

	const {
        href,
        active,
        children
    }: Props = $props();
</script>

<li class="nav-item">
	<a class="nav-link" class:active {href}>
		{@render children()}
	</a>
</li>

// Frontend/skillforge-react/src/components/nav-link/NavLink.tsx
import Link from 'next/link';
import { type ReactNode } from 'react';

export interface INavLinkProps {
    href: string;
    active?: boolean;
    children: ReactNode;
}

export function NavLink (props: INavLinkProps) {
  return (
    <li className="nav-item">
        <Link className={`nav-link ${props.active ? 'active' : ''}`} href={props.href}>
            {props.children}
        </Link>
    </li>
  );
}
