// Frontend/skillforge-react/src/components/tag-link-placeholder/TagLinkPlaceholder.tsx
import { BootstrapColor } from '@/lib/types/BootstrapColor';
import * as React from 'react';
import { LinkPlaceholder } from '../link-placeholder/LinkPlaceholder';

export interface ITagLinkPlaceholderProps {
	size?: 'normal' | 'small';
	background?: 'outline' | 'fill';
	color?: BootstrapColor;
}

export function TagLinkPlaceholder({
	size,
	background,
	color,
}: ITagLinkPlaceholderProps) {
	return (
		<LinkPlaceholder size={size} background={background} color={color} borderRadius={3} />
	);
}

// Frontend/skillforge-svelte/src/components/tag-link-placeholder/TagLinkPlaceholder.svelte
<script lang="ts">
	import type { BootstrapColor } from 'skillforge-common/types/BootstrapColor';
	import LinkPlaceholder from '../link-placeholder/LinkPlaceholder.svelte';

	interface Props {
		size?: 'normal' | 'small';
		background?: 'outline' | 'fill';
		color?: BootstrapColor;
	}

	let {
		size,
		background,
		color,
	}: Props = $props();
</script>

<LinkPlaceholder {size} {background} {color} borderRadius={3} />
