// Frontend/skillforge/src/components/comment/CommentLimitedPlaceholder.svelte
<script lang="ts">
	import AuthorBoxPlaceholder from "$components/user/AuthorBoxPlaceholder.svelte";
</script>

<AuthorBoxPlaceholder size="small" />
<div class="mx-5 p-3">
    <div class="content-wrapper rounded-3 p-3 placeholder col-12"></div>
</div>

<style>
    .content-wrapper {
        background-color: rgba(111, 66, 193, 50%);
        height: 72px;
    }
</style>

// Frontend/skillforge-react/src/components/comment-limited-placeholder/CommentLimitedPlaceholder.tsx
import * as React from 'react';
import { AuthorBoxPlaceholder } from '../author-box-placeholder/AuthorBoxPlaceholder';
import styles from './CommentLimitedPlaceholder.module.css';

export function CommentLimitedPlaceholder() {
	return (
		<>
			<AuthorBoxPlaceholder size="small" />
			<div className="mx-5 p-3">
				<div className={`${styles['content-wrapper']} rounded-3 p-3 placeholder col-12`}></div>
			</div>
		</>
	);
}
