// Frontend/skillforge-react/src/components/layout/three-columns/ThreeColumns.tsx
import { type ReactNode } from 'react';
import './_three-columns.scss';

export interface IThreeColumnsProps {
    classes?: string;
    leftColumn?: ReactNode;
    children: ReactNode;
    rightColumn?: ReactNode;
    hideLeftColumnOnMobile?: boolean;
    hideRightColumnOnMobile?: boolean;
}

export function ThreeColumns (props: IThreeColumnsProps) {
  return (
    <div className={`row flex-column flex-xl-row ${props.classes}`}>
        <div className={`left-column ${props.hideLeftColumnOnMobile ? 'd-none d-xl-block' : ''}`}>
            {props.leftColumn}
        </div>
        <div className="col-12 middle-column">
            {props.children}
        </div>
        <div className={`right-column ${props.hideRightColumnOnMobile ? 'd-none d-xl-block' : ''}`}>
            {props.rightColumn}
        </div>
    </div>
  );
}

// Frontend/skillforge/src/components/layout/ThreeColumns.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	interface Props {
		mod?: string;
		leftColumn?: Snippet;
		children: Snippet;
		rightColumn?: Snippet;
		hideLeftColumnOnMobile?: boolean;
		hideRightColumnOnMobile?: boolean;
	}

	const {
		mod,
		leftColumn,
		children,
		rightColumn,
		hideLeftColumnOnMobile,
		hideRightColumnOnMobile
	}: Props = $props();
</script>

<div class="row flex-column flex-xl-row {mod}">
	<div
		class="left-column"
		class:d-none={hideLeftColumnOnMobile}
		class:d-xl-block={hideLeftColumnOnMobile}
	>
		{@render leftColumn?.()}
	</div>
	<div class="col-12 middle-column">
		{@render children()}
	</div>
	<div
		class="right-column"
		class:d-none={hideRightColumnOnMobile}
		class:d-xl-block={hideRightColumnOnMobile}
	>
		{@render rightColumn?.()}
	</div>
</div>

<style>
	@media (min-width: 1200px) {
		.left-column {
			flex-basis: 20%;
		}

		.middle-column {
			flex-basis: 52%;
		}

		.right-column {
			flex-basis: 28%;
		}
	}
</style>
