// Frontend/skillforge-react/src/app/join/page.tsx
import { LoginForm } from "@/components/login-form/LoginForm";
import { RegisterForm } from "@/components/register-form/RegisterForm";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: 'SkillForge | Join us',
    description: 'Register or Login to SkillForge',
    robots: 'noindex,nofollow'
};

export default function Join() {
	return (
		<div className="row">
			<div className="col-12 col-lg-6">
				<LoginForm />
			</div>
			<div className="col-12 col-lg-6">
				<RegisterForm />
			</div>
		</div>
	);
}

// Frontend/skillforge/src/routes/join/+page.svelte
<script lang="ts">
	import LoginForm from '$components/login-form/LoginForm.svelte';
	import RegisterForm from '$components/register-form/RegisterForm.svelte';
</script>

<div class="row">
	<div class="col-12 col-lg-6">
		<LoginForm />
	</div>
	<div class="col-12 col-lg-6">
		<RegisterForm />
	</div>
</div>

<svelte:head>
	<title>SkillForge | Join us</title>
	<meta name="description" content="Register or Login to SkillForge" />
	<meta name="robots" content="noindex,nofollow" />
</svelte:head>
