// Frontend/skillforge-react/src/components/login-cta/LoginCta.tsx
'use client'

import * as React from 'react';
import { Block } from '../block/Block';
import Link from 'next/link';
import { useCurrentUser } from '@/hooks/useCurrentUser';

export interface ILoginCtaProps {
	ctaText: string;
	description: string;
	inline?: boolean;
}

export function LoginCta({
	ctaText,
	description,
	inline,
}: ILoginCtaProps) {
	const currentUser = useCurrentUser();

	if (!!currentUser) return '';

	return (
		<Block>
			<div className="card-text p-4">
				<div className="text-center">
					<Link href="/join" className="btn btn-primary text-decoration-none mb-2">{ctaText}</Link>
					<p className={`mb-0 ${inline ? 'd-inline ms-2' : ''}`}>{description}</p>
				</div>
			</div>
		</Block>
	);
}

// Frontend/skillforge/src/components/login-cta/LoginCta.svelte
<script lang="ts">
	import Block from "$components/layout/Block.svelte";
	import { currentUserStore } from "$lib/stores/currentUserStore";

    interface Props {
        ctaText: string,
        description: string
        inline?: boolean
    }

    let {
        ctaText,
        description,
        inline,
    }: Props = $props();
</script>

{#if !$currentUserStore}
    <Block>
        <div class="card-text p-4">
            <div class="text-center">
                <a href="/join" class="btn btn-primary text-decoration-none mb-2">{ctaText}</a>
                <p class="mb-0" class:d-inline={inline} class:ms-2={inline}>{description}</p>
            </div>
        </div>
    </Block>
{/if}
