// Frontend/skillforge-react/src/components/form/file-input-field/FileInputField.tsx
import { ChangeEventHandler } from "react";

export interface IFileInputFieldProps {
    id: string;
    name?: string;
    label?: string;
    onFilesChange?: (files: FileList | null) => void,
    value?: string;
    onValueChange?: (value: string) => void;
    accept?: string;
    classes?: string;
    disabled?: boolean;
    onChange?: ChangeEventHandler<HTMLInputElement>;
}

export function FileInputField({
    id,
    name = id,
    label = name,
    onFilesChange,
    value,
    onValueChange,
    accept,
    classes,
    disabled,
    onChange,
}: IFileInputFieldProps) {
    return (
        <div className="mb-4">
            <label htmlFor={id} className="form-label">{label}:</label>
            <input
                className={`form-control ${classes}`}
                type="file"
                id={id}
                name={name}
                accept={accept}
                value={value}
                onChange={e => {
                    onChange?.(e);
                    onValueChange?.(e.target.value);
                    onFilesChange?.(e.target.files);
                }}
                disabled={disabled}
            />
        </div>
    );
}

// Frontend/skillforge/src/components/form/FileInputField.svelte
<script lang="ts">
	import type { ChangeEventHandler } from "svelte/elements";

    interface Props {
        id: string,
        name?: string,
        label?: string,
        files?: FileList | null | undefined,
        value?: any,
        accept?: string,
        mod?: string,
        disabled?: boolean,
        onchange?: ChangeEventHandler<HTMLInputElement>,
    }

    var {
        id,
        name = id,
        label = name,
        files = $bindable(),
        value = $bindable(),
        accept,
        mod,
        disabled,
        onchange,
    }: Props = $props();
</script>

<div class="mb-4">
    <label for={id} class="form-label">{label}:</label>
    <input class="form-control {mod}" type="file" {id} {name} {accept} bind:files bind:value {onchange} {disabled}>
</div>
