// Frontend/skillforge-react/src/components/form/Form.tsx
import React from 'react';
import { useForm } from 'react-hook-form';
import { FormContext } from '../../context/FormContext';
import { requestApi } from "@/lib/api/client";
import type ErrorResponse from "@/lib/types/ErrorResponse";

export interface IFormProps<T> {
    action: string;
    method?: 'GET' | 'POST' | 'DIALOG';
    isMultipartFormData?: boolean;
    onSubmit?: (data: any) => any;
    onSuccess: (response: T) => void;
    children: React.ReactNode;
}

export function Form<T>({
    action,
    method = 'POST',
    isMultipartFormData = false,
    onSubmit = data => data,
    onSuccess,
    children,
}: IFormProps<T>) {
    const form = useForm({
        mode: 'onTouched'
    });

    async function submit(data: any) {
        let init: RequestInit = {
            method: method,
            credentials: 'include',
            headers: {
                'Accept': 'application/json',
            }
        };

        if (!isMultipartFormData) {
            init.headers = {
                ...init.headers,
                'Content-Type': 'application/json',
            };

            init.body = JSON.stringify(data);
        } else {
            let fd = new FormData();
            for (let fieldName in data) {
                fd.append(fieldName, data[fieldName] as string | Blob);
            }

            init.body = fd;
        }

        return requestApi(action, {
            init
        })
            .then(r => {
                onSuccess(r);
            })
            .catch((e: ErrorResponse) => {
                for (let fieldName in e.errors) {
                    let errors = e.errors[fieldName];

                    if (errors.length > 0) {
                        form.setError(fieldName, {
                            type: "backend",
                            message: errors[0]
                        });
                    }
                }

                if (e.detail || e.title) {
                    console.error(e.detail ?? e.title);
                }
            });
    }

    return (
        <form onSubmit={form.handleSubmit(data => submit(onSubmit(data)))}>
            <FormContext.Provider value={{
                form,
                submit: () => form.handleSubmit(data => submit(onSubmit(data)))()
            }}>
                {children}
            </FormContext.Provider>
        </form>
    );
}

// Frontend/skillforge/src/components/form/Form.svelte
<script lang="ts" generics="T">
	import type FormContext from "$lib/types/FormContext";
    import type ErrorResponse from "$lib/types/ErrorResponse";
	import type ValidationRule from "$lib/types/ValidationRule";
	import type ValidationRules from "$lib/types/ValidationRules";
	import { setContext, type Snippet } from "svelte";
	import { requestApi } from "$lib/api/client";

    interface Props {
        action: string,
        method?: 'GET' | 'POST' | 'DIALOG',
        formData: T,
        isMultipartFormData?: boolean,
        onSuccess: (response: any) => void,
        children: Snippet,
        validationRules?: ValidationRules
    }

    interface Fields {
        [key: string]: {
            validate: (onlyVisited: boolean) => string[] | null,
            setErrors: (errors: string[]) => void,
            errors: string[]
        }
    }

    const {
        action,
        method = 'POST',
        formData,
        isMultipartFormData = false,
        onSuccess,
        children,
        validationRules
    }: Props = $props();

    let fields: Fields = {};

    function registerField(
            name: string,
            validate: (onlyVisited: boolean) => string[] | null,
            setErrors: (errors: string[]) => void): void {

        fields[name] = {
            validate,
            setErrors,
            errors: []
        }
    }

    function updateField(name: string, errors: string[]): void {
        fields[name].errors = errors;
    }

    function getValidationRules(name: string): ValidationRule[] {
        if (typeof validationRules === 'undefined' || !(name in validationRules)) {
            return [];
        }

        return validationRules[name];
    }

    setContext<FormContext>('form', {
        registerField,
        updateField,
        getValidationRules,
        validateFields,
        submit,
    });

    export function validate(): boolean {
        let isValid = true;

        for (let fieldName in fields) {
            let fieldErrors = fields[fieldName].validate(false);

            if (fieldErrors == null) {
                // should never happen because onlyVisited argument is false in the validate function call.
                continue;
            }

            if (isValid && !!fieldErrors.length) {
                isValid = false;
            }
        }

        return isValid;
    }

    export function validateFields(fieldNames: string[]) {
        for (let fieldName of fieldNames) {
            fields[fieldName].validate(true);
        }
    }

    export async function submit() {
        if (!validate()) {
            return;
        }

        let init: RequestInit = {
            method,
            credentials: 'include',
            headers: {
                'Accept': 'application/json',
            }
        };

        if (!isMultipartFormData) {
            init.headers = {
                ...init.headers,
                'Content-Type': 'application/json',
            };

            init.body = JSON.stringify(formData);
        } else {
            let fd = new FormData();
            for (let fieldName in formData) {
                fd.append(fieldName, formData[fieldName] as string | Blob);
            }

            init.body = fd;
        }

        return requestApi(action, init)
            .then(r => {
                onSuccess(r);
            })
            .catch((e: ErrorResponse) => {
                for (let fieldName in e.errors) {
                    let errors = e.errors[fieldName];

                    if (fields[fieldName]) {
                        fields[fieldName].errors = errors;
                        fields[fieldName].setErrors(errors);
                    }
                }

                if (e.detail) {
                    console.error(e.detail);
                }
            })
    }
</script>

<form {action} {method} enctype={isMultipartFormData ? 'multipart/form-data' : undefined}>
    {@render children()}
</form>
