// Frontend/skillforge-react/src/components/form/image-loader/ImageLoader.tsx
import { Button } from '@/components/button/Button';
import { Icon } from '@/components/icon/Icon';
import { useState } from 'react';
import { uploadImage } from '@/lib/api/client';
import { ImageUploadType } from '@/lib/types/ImageUploadType';
import { getBackendUrl } from '@/lib/util';
import { FileInputField } from '../file-input-field/FileInputField';
import { useFormContext } from '@/context/FormContext';

export interface IImageLoaderProps {
    id: string;
    name?: string;
    label?: string;
    imageAlt: string;
    url: string | undefined;
    onUrlChange: (url?: string) => void;
    imageUploadType: ImageUploadType;
}

export function ImageLoader({
    id,
    name = id,
    label = name,
    imageAlt,
    url,
    onUrlChange,
    imageUploadType,
}: IImageLoaderProps) {
    const formContext = useFormContext();

    const [isLoading, setIsLoading] = useState<boolean>(false);
    const hasFile = !!url;
    const [files, setFiles] = useState<FileList | null>();

    async function onFilesChange(files: FileList | null) {
        let file: File | undefined = files?.[0];

        if (file) {
            setIsLoading(true);
            url = await uploadImage(file, imageUploadType);
            setIsLoading(false);

            onUrlChange?.(url);
            formContext.form.setValue(name, url);
        }

        setFiles?.(files);
    }

    function onRemoveClick() {
        url = undefined;
        onUrlChange?.(url);
        formContext.form.setValue(name, url);
    }

    return (
        <div className="mb-4">
            <FileInputField
                id={id}
                name={name}
                label={label}
                accept=".jpg, .jpeg, .png"
                onFilesChange={onFilesChange}
            />
            {isLoading ?
                <div className="position-relative m-4">
                    <div className="d-flex justify-content-center align-items-center" style={{
                        height: '150px'
                    }}>
                        <strong role="status">Loading...</strong>
                        <div className="spinner-border ms-3" aria-hidden="true"></div>
                    </div>
                </div>
                : hasFile ?
                    <div className="m-4 d-flex justify-content-center">
                        <div className="position-relative">
                            <img src={getBackendUrl(url)} alt={imageAlt} className="rounded preview-image" style={{ maxWidth: '250px' }} />
                            <div className="d-flex justify-content-end position-absolute start-0 top-0 end-0">
                                <Button color="danger" onClick={onRemoveClick}>
                                    <Icon type="trash-fill" />
                                </Button>
                            </div>
                        </div>
                    </div>
                    : ''}
        </div>
    );
}

// Frontend/skillforge/src/components/form/ImageLoader.svelte
<script lang="ts">
	import Icon from '$components/icon/Icon.svelte';
	import { PUBLIC_BACKEND_DOMAIN } from '$env/static/public';
	import { uploadImage } from '$lib/api/client';
	import type { ImageUploadType } from '$lib/types/ImageUploadType';
	import Button from '../button/Button.svelte';
	import FileInputField from './FileInputField.svelte';

	interface Props {
		id: string;
		name?: string;
		label?: string;
        imageAlt: string,
        url: string | undefined,
        imageUploadType: ImageUploadType
	}

    let {
        id,
        name = id,
        label = name,
        imageAlt,
        url = $bindable(),
        imageUploadType,
    }: Props = $props();

    let isLoading = $state<boolean>(false);
    let hasFile = $derived<boolean>(!!url);
    let files = $state<FileList>();
    let fileInputValue = $state<any>();

    async function onchange() {
        let file: File | undefined = files?.[0];

        if (file) {
            isLoading = true;
            url = await uploadImage(file, imageUploadType);
            isLoading = false;
        }
    }

    function onRemoveClick() {
        url = undefined;
        fileInputValue = '';
    }
</script>

<div class="mb-4">
    <FileInputField
        {id}
        {name}
        {label}
        accept=".jpg, .jpeg, .png"
        bind:files
        bind:value={fileInputValue}
        {onchange}
    />
    {#if isLoading}
        <div class="position-relative m-4">
            <div class="d-flex justify-content-center align-items-center" style="height: 150px">
                <strong role="status">Loading...</strong>
                <div class="spinner-border ms-3" aria-hidden="true"></div>
            </div>
        </div>
    {:else if hasFile}
        <div class="m-4 d-flex justify-content-center">
            <div class="position-relative">
                <img src={PUBLIC_BACKEND_DOMAIN + url} alt={imageAlt} class="rounded preview-image" />
                <div class="d-flex justify-content-end position-absolute start-0 top-0 end-0">
                    <Button color="danger" onclick={onRemoveClick}>
                        <Icon type="trash-fill" />
                    </Button>
                </div>
            </div>
        </div>
    {/if}
</div>

<style>
    .preview-image {
        max-width: 250px;
    }
</style>
