// Frontend/skillforge-react/src/components/form/radio-group/RadioGroup.tsx
import OptionType from "@/lib/types/OptionType";
import { ReactNode } from "react";
import { RadioField } from "../radio-field/RadioField";
import { useFormContext } from "@/context/FormContext";
import './_radio-group.scss';

export interface IRadioGroupProps {
    name: string;
    label?: string;
    options?: OptionType[];
    value?: any;
    onChange?: (value: any) => void;
    isSwitch?: boolean;
    isInline?: boolean;
    isReverse?: boolean;
    children?: ReactNode;
}

export function RadioGroup({
    name,
    label,
    options,
    value,
    onChange,
    isSwitch,
    isInline,
    isReverse,
    children,
}: IRadioGroupProps) {
    const formContext = useFormContext();
    const isInvalid = !!formContext?.form.formState.errors[name];

    return (
        <div className="mb-4">
            <div role="radiogroup" className={`radio-group ${isInvalid ? 'is-invalid' : ''}`}>
                {label && <strong className="d-inline-block mb-2">{label}:</strong>}
                {options && options?.map(({ Value, Label }) =>
                    <RadioField
                        id={`${name}-${Value}`}
                        key={Value}
                        name={name}
                        label={Label}
                        value={Value}
                        isSwitch={isSwitch}
                        isInline={isInline}
                        isReverse={isReverse}
                        selectedOption={value}
                        onChange={onChange}
                    />
                )}
                {children}
            </div>
            <div className="invalid-feedback">
                {isInvalid && formContext?.form.formState.errors[name]?.message as string}
            </div>
        </div>
    );
}

// Frontend/skillforge/src/components/form/RadioGroup.svelte
<script lang="ts">
	import type Option from "$lib/types/OptionType";
	import type { Snippet } from "svelte";
	import RadioField from "./RadioField.svelte";
	import FieldValidation from "./FieldValidation.svelte";
	import type ValidatedField from "$lib/types/ValidatedField";
    import './_radio-group.scss';

    interface Props {
        name: string,
        label?: string,
        options?: Option[],
        group?: any,
        isSwitch?: boolean,
        isInline?: boolean,
        isReverse?: boolean,
        validateTogether?: string[],
        children?: Snippet,
    }

    let {
        name,
        label,
        options,
        group = $bindable(),
        isSwitch,
        isInline,
        isReverse,
        validateTogether,
        children,
    }: Props = $props();

    let isValid = $state<boolean>(true);
    let isVisited = $state<boolean>(false);
    let fieldValidation: ValidatedField;
    let lastValue: any | null = null;

    $effect(() => {
        if (group !== lastValue) {
            fieldValidation.validate();

            lastValue = group;
            isVisited = true;
        }
    });
</script>

<div class="mb-4">
    <div role="radiogroup" class="radio-group" class:is-invalid={!isValid}>
        {#if label}
            <strong class="d-inline-block mb-2">{label}:</strong>
        {/if}
        {#if options}
            {#each options as { Value, Label }}
                <RadioField id="{name}-{Value}" {name} label={Label} value={Value} {isSwitch} {isInline} {isReverse} bind:group />
            {/each}
        {/if}
        {@render children?.()}
    </div>
    <FieldValidation {name}
        label={label ?? name}
        value={group}
        shouldValidate={isVisited}
        bind:isValid
        bind:this={fieldValidation}
        {validateTogether}
    />
</div>
