// Frontend/skillforge-react/src/components/modal/Modal.tsx
import { ReactNode } from "react";
import { Scrollable } from "../scrollable/Scrollable";
import { useClickOutside } from "@/hooks/useClickOutside";
import { AnimatePresence, motion } from "framer-motion";
import { ModalContext } from "@/context/ModalContext";
import './_modal.scss';

export interface IModalProps {
    children?: ReactNode;
    header?: ReactNode;
    footer?: ReactNode;
    show: boolean;
    setShow: (show: boolean) => void;
    size?: 'default' | 'sm' | 'lg' | 'xl';
    verticallyCentered?: boolean;
    scrollable?: boolean;
}

export function Modal({
    children,
    header,
    footer,
    show,
    setShow,
    size = 'default',
    verticallyCentered,
    scrollable
}: IModalProps) {
    function close() {
        setShow(false);
    }

    const clickOutsideRef = useClickOutside<HTMLDivElement>(close);

    if (!show) return null;

    return (
        <AnimatePresence>
            <motion.aside
                key="modal"
                className="modal fade show d-block"
                tabIndex={-1}
                aria-modal={show ? 'true' : undefined}
                role={show ? 'dialog' : undefined}
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.15 }}
            >
                <ModalContext.Provider value={{
                    close
                }}>
                    <div
                        className={`modal-dialog modal-fullscreen-sm-down ${size === 'default' ? '' : `modal-${size}`} ${verticallyCentered ? 'modal-dialog-centered' : ''} ${scrollable ? 'modal-dialog-scrollable' : ''}`}
                        ref={clickOutsideRef}
                    >
                        <div className="modal-content">
                            {header}
                            {scrollable ? (
                                <Scrollable className="modal-body">
                                    {children}
                                </Scrollable>
                            ) : (
                                <div className="modal-body">
                                    {children}
                                </div>
                            )}
                            {footer &&
                                <div className="modal-footer">
                                    {footer}
                                </div>
                            }
                        </div>
                    </div>
                </ModalContext.Provider>
            </motion.aside>
            <div className="modal-backdrop show"></div>
        </AnimatePresence>
    );
}

// Frontend/skillforge/src/components/modal/Modal.svelte
<script lang="ts">
	import Scrollable from '$components/scrollable/Scrollable.svelte';
	import { setContext, type Snippet } from 'svelte';
	import { fade } from 'svelte/transition';
    import './_modal.scss';
	import { clickOutside } from '$lib/util';
	import type ModalContext from '$lib/types/ModalContext';

	interface Props {
		children?: Snippet;
        header?: Snippet,
		footer?: Snippet;
        show: boolean,
		size?: 'default' | 'sm' | 'lg' | 'xl';
		verticallyCentered?: boolean;
		scrollable?: boolean;
	}

	let {
		children,
        header,
		footer,
        show = $bindable<boolean>(false),
		size = 'default',
		verticallyCentered,
		scrollable
	}: Props = $props();

    setContext<ModalContext>('modal', {
        close
    });

    export function close() {
        show = false;
    }
</script>

{#if show}
    <aside
        class="modal fade show d-block"
        tabindex="-1"
        aria-modal={show ? 'true' : undefined}
        role={show ? 'dialog' : undefined}
        transition:fade={{ duration: 100 }}
    >
        <div
            class="modal-dialog modal-fullscreen-sm-down {size === 'default' ? '' : `modal-${size}`}"
            class:modal-dialog-centered={verticallyCentered}
            class:modal-dialog-scrollable={scrollable}
            use:clickOutside={close}
        >
            <div class="modal-content">
                {@render header?.()}
                {#if children}
                    {#if scrollable}
                        <Scrollable class="modal-body">
                            {@render children()}
                        </Scrollable>
                    {:else}
                        <div class="modal-body">
                            {@render children()}
                        </div>
                    {/if}
                {/if}
                {#if footer}
                    <div class="modal-footer">
                        {@render footer()}
                    </div>
                {/if}
            </div>
        </div>
    </aside>
    <div class="modal-backdrop show"></div>
{/if}
