// Frontend/skillforge-react/src/components/follow-button/FollowButton.tsx
import { Button } from '@/components/button/Button';
import { followTag, followUser, unfollowTag, unfollowUser } from '@/lib/api/client';

export interface IFollowButtonProps {
    subjectName: string;
    type: 'user' | 'tag';
    isFollowedByCurrentUser?: boolean;
    setIsFollowedByCurrentUser?: (f: boolean) => void;
    btnSize?: 'md' | 'sm';
}

export function FollowButton({ subjectName, type, isFollowedByCurrentUser, setIsFollowedByCurrentUser, btnSize = 'md' }: IFollowButtonProps) {
    const followFunctions = {
        user: followUser,
        tag: followTag
    };

    const unfollowFunctions = {
        user: unfollowUser,
        tag: unfollowTag
    };

    async function follow() {
        await followFunctions[type](subjectName);

        setIsFollowedByCurrentUser?.(true);
    }

    async function unfollow() {
        await unfollowFunctions[type](subjectName);

        setIsFollowedByCurrentUser?.(false);
    }

    return (
        <>
            {isFollowedByCurrentUser ? (
                <Button onClick={unfollow} size={btnSize} classes="follow-button" isOutline>Unfollow</Button>
            ) : (
                <Button onClick={follow} size={btnSize} classes="follow-button border border-2 border-primary">Follow</Button>
            )}
        </>
    );
}

// Frontend/skillforge/src/components/button/FollowButton.svelte
<script lang="ts">
	import { followTag, followUser, unfollowTag, unfollowUser } from "$lib/api/client";
	import Button from "./Button.svelte";

    interface Props {
        subjectName: string,
        type: 'user' | 'tag',
        isFollowedByCurrentUser: boolean,
        btnSize?: 'md' | 'sm'
    }

    let {
        subjectName,
        type,
        isFollowedByCurrentUser = $bindable<boolean>(),
        btnSize = 'md',
    }: Props = $props();

    const followFunctions = {
        user: followUser,
        tag: followTag
    }

    const unfollowFunctions = {
        user: unfollowUser,
        tag: unfollowTag
    }

	async function follow() {
		await followFunctions[type](subjectName);

        isFollowedByCurrentUser = true;
	}

	async function unfollow() {
		await unfollowFunctions[type](subjectName);

        isFollowedByCurrentUser = false;
	}
</script>

{#if isFollowedByCurrentUser}
    <Button onclick={unfollow} size={btnSize} isOutline>Unfollow</Button>
{:else}
    <Button onclick={follow} size={btnSize} mod="border border-2 border-primary">Follow</Button>
{/if}
