// Frontend/skillforge/src/components/dropdown/Dropdown.svelte
<script lang="ts">
	import { clickOutside } from '$lib/util';
	import { type Snippet } from 'svelte';
	import { fade } from 'svelte/transition';

	interface Props {
		isNav?: boolean;
		buttonSnippet: Snippet;
		children: Snippet;
	}

	const {
        isNav,
        buttonSnippet,
        children
    }: Props = $props();

	let isOpen = $state(false);

	function onclick() {
		isOpen = !isOpen;
	}

	function closeDropdown() {
		isOpen = false;
	}
</script>

{#if isNav}
	<li class="dropdown nav-item">
		<button
			class="dropdown-toggle nav-link text-start w-100"
			{onclick}
			type="button"
			aria-label="Button"
			aria-expanded={isOpen}
			use:clickOutside={closeDropdown}
		>
			{@render buttonSnippet()}
		</button>
		{#if isOpen}
			<ul class="dropdown-menu show" transition:fade={{ duration: 100 }}>
				{@render children()}
			</ul>
		{/if}
	</li>
{:else}
	<div class="btn-group">
		<button
			class="dropdown-toggle btn btn-outline-primary rounded-3 border-1"
			{onclick}
			type="button"
			aria-label="Button"
			aria-expanded={isOpen}
			use:clickOutside={closeDropdown}
		>
			{@render buttonSnippet()}
		</button>
		{#if isOpen}
			<ul class="dropdown-menu show" transition:fade={{ duration: 100 }}>
				{@render children()}
			</ul>
		{/if}
	</div>
{/if}

<style lang="scss">
	.dropdown-toggle {
		&::after {
			display: none;
		}
	}

	.dropdown-menu {
		top: 100%;
		left: 0;
		margin-top: var(--bs-dropdown-spacer);
		background-color: #30115e;
	}
</style>

// Frontend/skillforge-react/src/components/dropdown/Dropdown.tsx
import { useClickOutside } from '../../hooks/useClickOutside';
import React, { useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import styles from './Dropdown.module.scss';

export interface IDropdownProps {
    menuClass?: string;
    isNav?: boolean;
    buttonSnippet: React.ReactNode;
    children: React.ReactNode;
}

export function Dropdown(props: IDropdownProps) {
    const [isOpen, setIsOpen] = useState<boolean>(false);

    function onClick() {
        setIsOpen(!isOpen);
    }

    function closeDropdown() {
        setIsOpen(false);
    }

    function renderMenu() {
        return (
            <>
                {isOpen &&
                    <AnimatePresence>
                        <motion.ul className={`dropdown-menu ${styles['dropdown-menu']} show ${props.menuClass}`}
                            data-bs-popper="static"
                            initial={{ opacity: 0 }}
                            animate={{ opacity: 1 }}
                            exit={{ opacity: 0 }}
                            transition={{ duration: 0.1 }}
                        >
                            {props.children}
                        </motion.ul>
                    </AnimatePresence>
                }
            </>
        );
    }

    return (
        <>
            {props.isNav ? (
                <li className="dropdown nav-item">
                    <button
                        className={`dropdown-toggle ${styles['dropdown-toggle']} nav-link text-start w-100`}
                        onClick={onClick}
                        type="button"
                        aria-label="Button"
                        aria-expanded={isOpen}
                        ref={useClickOutside(closeDropdown)}
                    >
                        {props.buttonSnippet}
                    </button>
                    {renderMenu()}
                </li>
            ) : (
                <div className="btn-group">
                    <button
                        className={`dropdown-toggle ${styles['dropdown-toggle']} btn btn-outline-primary rounded-3 border-1`}
                        onClick={onClick}
                        type="button"
                        aria-label="Button"
                        aria-expanded={isOpen}
                        ref={useClickOutside(closeDropdown)}
                    >
                        {props.buttonSnippet}
                    </button>
                    {renderMenu()}
                </div>
            )}
        </>
    );
}
