// Frontend/skillforge-react/src/app/article/create/page.tsx
import { ArticleUpsertForm } from "@/components/article-upsert-form/ArticleUpsertForm";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { getCurrentUser, loadArticleUpsertPage } from "@/lib/api/client";
import { JWT_TOKEN_COOKIE_NAME } from "@/lib/auth";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: 'SkillForge | Create article',
    description: 'Create article',
    robots: 'noindex,nofollow'
};

export default async function ArticleCreate() {
    const cookieContext = await cookies();
    const authToken = cookieContext.get(JWT_TOKEN_COOKIE_NAME)?.value;

    const currentUserInfo = await getCurrentUser(authToken);

    if (!currentUserInfo) {
        throw redirect('/join');
    }

    let pageModel = await loadArticleUpsertPage(authToken);

    return <ArticleUpsertForm page={pageModel} />
}

// Frontend/skillforge-svelte/src/routes/article/create/+page.svelte
<script lang="ts">
	import type ArticleUpsertPageModel from '$lib/types/ArticleUpsertPageModel';
	import { setContext } from 'svelte';
	import ArticleUpsertForm from '$components/article-upsert-form/ArticleUpsertForm.svelte';

	interface Props {
		data: ArticleUpsertPageModel;
	}

	let { data }: Props = $props();

	setContext('page', data);
</script>

<svelte:head>
	<title>SkillForge | Create article</title>
	<meta name="description" content="Create article" />
	<meta name="robots" content="noindex,nofollow" />
</svelte:head>

<ArticleUpsertForm />
