// Frontend/skillforge-react/src/components/navbar/Navbar.tsx
import { AnimatePresence, motion } from 'framer-motion';
import { useClickOutside } from '../../hooks/useClickOutside';
import { useEffect, useState, type ReactNode } from 'react';
import Link from 'next/link';

export interface INavbarProps {
    logoLink: string;
    logoSnippet: ReactNode;
    children?: ReactNode;
    linksSnippet?: () => ReactNode;
}

export function Navbar(props: INavbarProps) {
    const [isOpen, setIsOpen] = useState(false);
    const [windowWidth, setWindowWidth] = useState<number>(1400);
    const isHamburgerMenu = windowWidth <= 991;

    function onTogglerClick() {
        setIsOpen(!isOpen);
    }

    function closeMenu() {
        setIsOpen(false);
    }

    function updateWindowWidth() {
        setWindowWidth(window.innerWidth);
    }

    useEffect(() => {
        updateWindowWidth();

        window.addEventListener('resize', updateWindowWidth);

        return () => {
            window.removeEventListener('resize', updateWindowWidth);
        };
    });

    return (
        <nav className="navbar navbar-expand-lg fixed-top bg-primary navbar-main" ref={useClickOutside(closeMenu)}>
            <div className="container">
                <Link className="navbar-brand" href={props.logoLink} title="To homepage">
                    {props.logoSnippet}
                </Link>
                <div className="d-flex justify-content-center flex-shrink-1" style={{ flexGrow: 0.5 }}>
                    <div className="w-100">
                        {props.children}
                    </div>
                </div>
                <button
                    className={`navbar-toggler ${!isOpen ? 'collapsed' : ''}`}
                    onClick={onTogglerClick}
                    type="button"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    <span className="navbar-toggler-icon"></span>
                </button>

                <AnimatePresence>
                    {(!isHamburgerMenu || isOpen) &&
                        <motion.div
                            className={`collapse navbar-collapse justify-content-end flex-shrink-0 flex-grow-0
                                ${isHamburgerMenu
                                    ? 'position-absolute start-0 end-0 navbar bg-primary'
                                    : ''}
                                ${isOpen ? 'show' : ''}`}
                            style={{
                                top: isHamburgerMenu ? '54px' : 'auto'
                            }}
                            id="navbarNavDropdown"
                            initial="hidden"
                            animate="visible"
                            exit="hidden"
                            variants={{
                                hidden: { y: -15, opacity: 0.0 },
                                visible: { y: 0, opacity: 1.0 },
                            }}
                            transition={{ duration: 0.1 }}
                        >
                            <ul
                                className={`navbar-nav ${isHamburgerMenu
                                    ? 'container text-start justify-content-start align-items-start'
                                    : ''}`}
                                style={{
                                    paddingLeft: isHamburgerMenu ? '0.75rem' : 'inherit'
                                }}
                            >
                                {props.linksSnippet?.()}
                            </ul>
                        </motion.div>
                    }
                </AnimatePresence>
            </div>
        </nav>
    );
}

// Frontend/skillforge-svelte/src/components/navbar/Navbar.svelte
<script lang="ts">
	import { onNavigate } from '$app/navigation';
	import { clickOutside } from '$lib/svelte-util';
	import type { Snippet } from 'svelte';
	import { fade, fly } from 'svelte/transition';

	interface Props {
		logoLink: string;
		logoSnippet: Snippet;
		children?: Snippet;
		linksSnippet?: Snippet;
	}

	const { logoLink, logoSnippet, children, linksSnippet }: Props = $props();

	let isOpen = $state(false);
	let windowWidth = $state<number>(1400);
	let isHamburgerMenu = $derived<boolean>(windowWidth <= 991);

	function onTogglerClick() {
		isOpen = !isOpen;
	}

	function closeMenu() {
		isOpen = false;
	}
	
    onNavigate(() => {
        closeMenu();
    });
</script>

<svelte:window bind:innerWidth={windowWidth} />

<nav class="navbar navbar-expand-lg fixed-top bg-primary navbar-main" use:clickOutside={closeMenu}>
	<div class="container">
		<a class="navbar-brand" href={logoLink} title="To homepage">
			{@render logoSnippet()}
		</a>
		<div class="d-flex justify-content-center flex-shrink-1" style:flex-grow="0.5">
			<div class="w-100">
				{@render children?.()}
			</div>
		</div>
		<button
			class="navbar-toggler"
			class:collapsed={!isOpen}
			onclick={onTogglerClick}
			type="button"
			aria-controls="navbarNavDropdown"
			aria-expanded="false"
			aria-label="Toggle navigation"
		>
			<span class="navbar-toggler-icon"></span>
		</button>

		{#if !isHamburgerMenu || isOpen}
			<div
				class="collapse navbar-collapse justify-content-end flex-shrink-0 flex-grow-0 {isHamburgerMenu
					? 'position-absolute start-0 end-0 navbar bg-primary'
					: ''}"
				class:show={isOpen}
				style:top={isHamburgerMenu ? '54px' : 'auto'}
				id="navbarNavDropdown"
				in:fly={{ y: -15, duration: 100 }}
				out:fly={{ y: -15, duration: 100 }}
			>
				<ul
					class="navbar-nav {isHamburgerMenu
						? 'container text-start justify-content-start align-items-start'
						: ''}"
					style:padding-left={isHamburgerMenu ? '0.75rem' : 'inherit'}
				>
					{@render linksSnippet?.()}
				</ul>
			</div>
		{/if}
	</div>
</nav>

<style>
	.navbar-main {
		view-transition-name: header;
	}
</style>
