// Frontend/skillforge-react/src/components/layout/two-columns/TwoColumns.tsx
import { type ReactNode } from 'react';
import './_two-columns.scss';

export interface ITwoColumnsProps {
    classes?: string;
    leftColumn?: ReactNode;
    children: ReactNode;
}

export function TwoColumns(props: ITwoColumnsProps) {
    return (
        <div className={`row ${props.classes}`}>
            <div className="d-none d-lg-block left-column">
                {props.leftColumn}
            </div>
            <div className="col-12 main-column">
                {props.children}
            </div>
        </div>
    );
}

// Frontend/skillforge-svelte/src/components/layout/TwoColumns.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	interface Props {
		mod?: string;
		leftColumn?: Snippet;
		children: Snippet;
	}

	const { mod, leftColumn, children }: Props = $props();
</script>

<div class="row {mod}">
	<div class="d-none d-lg-block left-column">
		{@render leftColumn?.()}
	</div>
	<div class="col-12 main-column">
		{@render children()}
	</div>
</div>

<style>
	@media (min-width: 992px) {
		.left-column {
			flex-basis: 25%;
		}

		.main-column {
			flex-basis: 75%;
		}
	}
</style>
