// Frontend/skillforge-svelte/src/components/modal-header/ModalHeader.svelte
<script lang="ts">
	import type ModalContext from "$lib/types/ModalContext";
	import { getContext } from "svelte";

    interface Props {
        title?: string
    }

    let {
        title
    }: Props = $props();

    let modalContext = getContext<ModalContext>('modal');
</script>

<div class="modal-header">
    <h2 class="modal-title fs-5">{title}</h2>
    <button type="button" class="btn-close" aria-label="Close" onclick={modalContext.close}></button>
</div>

// Frontend/skillforge-react/src/components/modal-header/ModalHeader.tsx
import { useModalContext } from '@/context/ModalContext';

export interface IModalHeaderProps {
    title?: string;
}

export function ModalHeader({ title }: IModalHeaderProps) {
    const modalContext = useModalContext();

    return (
        <div className="modal-header">
            <h2 className="modal-title fs-5">{title}</h2>
            <button type="button" className="btn-close" aria-label="Close" onClick={modalContext.close}></button>
        </div>
    );
}
