// Frontend/skillforge-react/src/components/anchor-list/AnchorList.tsx
import { Block } from '@components/block/Block';
import { type ReactNode } from 'react';

export interface IAnchorListProps<T> {
    title: string;
    items: T[];
    itemSnippet: (item: T) => ReactNode;
}

export function AnchorList<T> ({ title, items, itemSnippet }: IAnchorListProps<T>) {
  return (
    <Block header={<h3 className="card-title h4">{title}</h3>}>
        <div className="card-body">
            <ul className="list-group rounded-3">
                {items.map(itemSnippet)}
            </ul>
        </div>
    </Block>
  );
}

// Frontend/skillforge/src/components/anchor-list/AnchorList.svelte
<script lang="ts" generics="T">
	import Block from '$components/block/Block.svelte';
	import type { Snippet } from 'svelte';

	interface Props {
		title: string;
		items: T[];
		itemSnippet: Snippet<[T]>;
	}

	let {
        title,
        items,
        itemSnippet
    }: Props = $props();
</script>

<Block>
	{#snippet header()}
		<h3 class="card-title h4">{title}</h3>
	{/snippet}
	<div class="card-body">
		<ul class="list-group rounded-3">
			{#each items as item}
				{@render itemSnippet(item)}
			{/each}
		</ul>
	</div>
</Block>
