// Frontend/skillforge-svelte/src/components/author-box/AuthorBox.svelte
<script lang="ts">
	import Icon from "$components/icon/Icon.svelte";
	import { formatRelativeTime, getImagePath } from "skillforge-common/util";
	import moment from "moment";

    interface Props {
        name: string,
        avatarImage: string | null | undefined,
        date: string,
        editedDate?: string,
        mod?: string,
        size?: 'normal' | 'small',
        indent?: boolean
    }

    let {
        name,
        avatarImage,
        date,
        editedDate,
        mod,
        size = 'normal',
        indent = true,
    }: Props = $props();
</script>

<div class="author-box d-flex gap-2 size-{size} {mod}" class:ms-2={indent}>
	<div class="author-box__image-wrapper d-flex flex-column justify-content-start align-items-end" class:w-auto={!indent}>
        <a href="/user/{name}" class="text-decoration-none">
		    <img src="{getImagePath(avatarImage)}" class="author-box__image round-image" alt="Robert profile" />
        </a>
	</div>
	<div class="author-box__info-col d-flex flex-column">
        <a href="/user/{name}" class="text-decoration-none">{name}</a>
        <div class="small text-tertiary">
            <time datetime={moment(date).format('YYYY-MM-DD HH:mm')}>
                {moment(date).format('ddd, D MMMM, YYYY HH:mm')}
            </time>
            <span class="text-muted ms-2">({formatRelativeTime(date)})</span>
        </div>
        {#if editedDate}
            <div class="small text-info-emphasis">
                <Icon type="pencil-fill" />
                <time datetime={moment(editedDate).format('YYYY-MM-DD HH:mm')}>
                    {moment(editedDate).format('ddd, D MMMM, YYYY HH:mm')}
                </time>
                <span class="ms-2">({formatRelativeTime(editedDate)})</span>
            </div>
        {/if}
	</div>
</div>

<style lang="scss">
	.author-box {
        &__image {
            &-wrapper {
                width: 48px;
            }
        }

        &.size-normal {
            .author-box__image {
                width: 40px;
            }
        }

        &.size-small {
            font-size: 14px;

            .author-box__image {
                width: 30px;
            }
        }
	}
</style>

// Frontend/skillforge-react/src/components/author-box/AuthorBox.tsx
import moment from 'moment';
import { Icon } from '../icon/Icon';
import { getImagePath, formatRelativeTime } from 'skillforge-common/util';
import Link from 'next/link';
import './_author-box.scss';

export interface IAuthorBoxProps {
    name: string;
    avatarImage: string | null | undefined;
    date: string;
    editedDate?: string;
    classes?: string;
    size?: 'normal' | 'small';
    indent?: boolean;
}

export function AuthorBox({
    name,
    avatarImage,
    date,
    editedDate,
    classes,
    size = 'normal',
    indent = true,
}: IAuthorBoxProps) {
    return (
        <div className={`author-box d-flex gap-2 size-${size} ${classes} ${indent ? 'ms-2' : ''}`}>
            <div className={`author-box__image-wrapper d-flex flex-column justify-content-start align-items-end ${!indent ? 'w-auto' : ''}`}>
                <Link href={`/user/${name}`} className="text-decoration-none">
                    <img src={getImagePath(avatarImage)} className="author-box__image round-image" alt="Robert profile" />
                </Link>
            </div>
            <div className="author-box__info-col d-flex flex-column">
                <Link href={`/user/${name}`} className="text-decoration-none">{name}</Link>
                <div className="small text-tertiary">
                    <time dateTime={moment(date).format('YYYY-MM-DD HH:mm')}>
                        {moment(date).format('ddd, D MMMM, YYYY HH:mm')}
                    </time>
                    <span className="text-muted ms-2">({formatRelativeTime(date)})</span>
                </div>
                {editedDate &&
                    <div className="small text-info-emphasis">
                        <Icon type="pencil-fill" />
                        <time dateTime={moment(editedDate).format('YYYY-MM-DD HH:mm')}>
                            {moment(editedDate).format('ddd, D MMMM, YYYY HH:mm')}
                        </time>
                        <span className="ms-2">({formatRelativeTime(editedDate)})</span>
                    </div>
                }
            </div>
        </div>
    );
}
