// Frontend/skillforge-svelte/src/components/tag-list-item/TagListItem.svelte
<script lang="ts">
	import FollowButton from "$components/follow-button/FollowButton.svelte";
	import TagLink from "$components/tag-link/TagLink.svelte";
	import { currentUserStore } from "$lib/stores/currentUserStore";
	import type TagListItemType from "skillforge-common/types/TagListItemType";

    interface Props {
        data: TagListItemType,
        mod?: string
    }

    let {
        data,
        mod
    }: Props = $props();
</script>

<div class="d-flex justify-content-center justify-content-lg-between align-items-center {mod}">
    <TagLink data={data.Link} />
    {#if $currentUserStore}
        <FollowButton
            subjectName={data.Link.Name}
            type="tag"
            bind:isFollowedByCurrentUser={data.IsFollowedByCurrentUser}
            btnSize="sm"
        />
    {/if}
</div>

// Frontend/skillforge-react/src/components/tag-list-item/TagListItem.tsx
'use client';

import { TagLink } from '../tag-link/TagLink';
import { FollowButton } from '../follow-button/FollowButton';
import TagListItemType from '@/lib/types/TagListItemType';
import { useCurrentUser } from '@/hooks/useCurrentUser';

export interface ITagListItemProps {
    data: TagListItemType;
    classes?: string;
}

export function TagListItem({
    data,
    classes = ''
}: ITagListItemProps) {
    const { currentUser } = useCurrentUser();

    return (
        <div className={`d-flex justify-content-center justify-content-lg-between align-items-center ${classes}`}>
            <TagLink data={data.Link} />
            {currentUser &&
                <FollowButton
                    subjectName={data.Link.Name}
                    type="tag"
                    isFollowedByCurrentUser={data.IsFollowedByCurrentUser}
                    btnSize="sm"
                />
            }
        </div>
    );
}
