// Frontend/skillforge/src/components/auth/RegisterForm.svelte
<script lang="ts">
	import Form from '../form/Form.svelte';
	import InputField from '../form/InputField.svelte';
	import type ValidationRules from '$lib/types/ValidationRules';
	import { compare, email, password, remote, required } from '$lib/validation/rules';
	import type UserRegisterCredentials from '$lib/types/UserRegisterCredentials';
	import { writable } from 'svelte/store';
	import Button from '../button/Button.svelte';
	import type UserInfo from '$lib/types/UserInfo';
	import { currentUserStore } from '$lib/stores/currentUserStore';
	import { goto } from '$app/navigation';
	import { addToast } from '$lib/stores/toastStore';

	let formData = writable<UserRegisterCredentials>({
		Username: '',
		Email: '',
		Password: '',
		ConfirmPassword: ''
	});

	let validationRules: ValidationRules = {
		Username: [
			{
				validate: required,
				message: () => `Please enter a valid username.`
			},
			{
				validate: (val) => remote('/User/VerifyUniqueUsername', 'name', val),
				message: () => 'Username is already taken.'
			}
		],
		Email: [
			{
				validate: required,
				message: () => `Please enter a valid e-mail.`
			},
			{
				validate: email,
				message: () => 'Invalid e-mail format.'
			},
			{
				validate: (val) => remote('/User/VerifyUniqueEmail', 'email', val),
				message: () => 'E-mail is already taken.'
			}
		],
		Password: [
			{
				validate: required,
				message: () => `Please enter a valid password.`
			},
			{
				validate: password,
				message: () =>
					'The password must be at least 8 characters long, contain at least one lowercase and uppercase letter, and at least one symbol.'
			}
		],
		ConfirmPassword: [
			{
				validate: required,
				message: () => `Please confirm your password.`
			},
			{
				validate: (val) => compare(val, $formData.Password),
				message: () => `Passwords don't match.`
			}
		]
	};

	function onRegisterSuccess() {
		let userInfo: UserInfo = {
			Id: 0,
			Name: $formData.Username,
			Email: $formData.Email,
			AvatarPath: ''
		};

		currentUserStore.set(userInfo);

		addToast('Registration successful');

		goto('/user/' + userInfo.Name);
	}
</script>

<section class="mb-5">
	<h2>Sign up</h2>
	<Form
		action="/User/Register"
		method="POST"
		formData={$formData}
		onSuccess={onRegisterSuccess}
		{validationRules}
		resetMode="onsuccess"
	>
		<div class="row">
			<div class="col-12">
				<InputField id="Username" type="text" label="Username" bind:value={$formData.Username} />
			</div>
			<div class="col-12">
				<InputField id="Email" type="email" label="E-mail" bind:value={$formData.Email} />
			</div>
			<div class="col-12">
				<InputField
					id="RegistrationPassword"
					name="Password"
					type="password"
					label="Password"
					bind:value={$formData.Password}
					validateTogether={['ConfirmPassword']}
				/>
			</div>
			<div class="col-12">
				<InputField
					id="ConfirmPassword"
					type="password"
					label="Confirm password"
					bind:value={$formData.ConfirmPassword}
				/>
			</div>
		</div>

        <div class="text-center text-lg-start">
		    <Button size="lg" isSubmitButton={true}>Sign up</Button>
        </div>
	</Form>
</section>

// Frontend/skillforge-react/src/components/register-form/RegisterForm.tsx
'use client'

import { Form } from '@/components/form/Form';
import { InputField } from '@/components/form/input-field/InputField';
import { useState } from 'react';
import type RegisterResponse from '@/lib/types/RegisterResponse';
import { remote, email as validateEmail, password as validatePassword } from '@/lib/validation/rules';
import { Button } from '@/components/button/Button';
import { useCurrentUser } from '../../hooks/useCurrentUser';
import type UserInfo from '@/lib/types/UserInfo';
import { storeAuthToken } from '@/lib/auth';
import { useToast } from '../../hooks/useToast';
import { useRouter } from 'next/navigation';

export function RegisterForm() {
    const [username, setUsername] = useState<string>('');
    const [email, setEmail] = useState<string>('');
    const [password, setPassword] = useState<string>('');
    const [confirmPassword, setConfirmPassword] = useState<string>('');

    const { setCurrentUser } = useCurrentUser();
    const router = useRouter();
    const { addToast } = useToast();

    function onSuccess(response: RegisterResponse) {
        let userInfo: UserInfo = {
            Name: username,
            Email: email,
            AvatarPath: ''
        };

        setCurrentUser(userInfo);
        storeAuthToken(response.AuthToken);

		addToast('Registration successful');

        router.push('/user/' + userInfo.Name);
    }

    return (
        <section className="mb-5">
            <h2>Sign up</h2>
            <Form<RegisterResponse>
                action="/User/Register"
                method="POST"
                onSuccess={onSuccess}
            >
                <div className="row">
                    <div className="col-12">
                        <InputField
                            id="Username"
                            type="text"
                            label="Username"
                            value={username}
                            onChange={setUsername}
                            options={{
                                required: "Please enter a valid username.",
                                validate: async (value) => await remote('/User/VerifyUniqueUsername', 'name', value) || "Username is already taken."
                            }}
                        />
                    </div>
                    <div className="col-12">
                        <InputField
                            id="Email"
                            type="email"
                            label="E-mail"
                            value={email}
                            onChange={setEmail}
                            options={{
                                required: "Please enter a valid e-mail.",
                                validate: async (value) => {
                                    if (!validateEmail(value)) return "Invalid e-mail format";
                                    if (!await remote('/User/VerifyUniqueEmail', 'email', value)) return "E-mail is already taken.";

                                    return true;
                                }
                        }} />
                    </div>
                    <div className="col-12">
                        <InputField
                            id="RegistrationPassword"
                            name="Password"
                            type="password"
                            label="Password"
                            value={password} onChange={setPassword}
                            options={{
                                required: "Please enter a valid password.",
                                validate: (value) => validatePassword(value) || "The password must be at least 8 characters long, contain at least one lowercase and uppercase letter, and at least one symbol."
                            }}
                            validateTogether={['ConfirmPassword']}
                        />
                    </div>
                    <div className="col-12">
                        <InputField
                            id="ConfirmPassword"
                            type="password"
                            label="Confirm password"
                            value={confirmPassword}
                            onChange={setConfirmPassword}
                            options={{
                                required: "Please confirm your password.",
                                validate: (value, fieldValues) => value === fieldValues.Password || "Passwords don't match."
                            }}
                        />
                    </div>
                </div>

                <div className="text-center text-lg-start">
                    <Button size="lg" isSubmitButton={true}>Sign up</Button>
                </div>
            </Form>
        </section>
    );
}
