// Frontend/skillforge-react/src/components/scrollable/Scrollable.tsx
import { ScrollableContext } from "@/context/ScrollableContext";
import ScrollableStore from "@/lib/types/ScrollableStore";
import { useRef } from "react";

export function Scrollable(props: any) {
    const scrollableElement = useRef<HTMLDivElement>(null);
    const onScrollCallbacks = useRef<(() => void)[]>(null);
    const scrollableContext = useRef<ScrollableStore>({
        getClientHeight: () => {
            return scrollableElement.current
                ? scrollableElement.current.getBoundingClientRect().top + scrollableElement.current.clientHeight
                : 0;
        },
        onScroll: (callback: () => void) => {
            onScrollCallbacks.current?.push(callback);
        }
    });

    function onScroll() {
        onScrollCallbacks.current?.forEach((cb) => cb());
    }

    return (
        <ScrollableContext.Provider value={scrollableContext.current}>
            <div {...props} ref={scrollableElement} onScroll={onScroll}>
                {props.children}
            </div>
        </ScrollableContext.Provider>
    );
}

// Frontend/skillforge/src/components/scrollable/Scrollable.svelte
<script lang="ts">
	import type ScrollableStore from '$lib/types/ScrollableStore';
	import { setContext } from 'svelte';
	import { writable } from 'svelte/store';

	let props = $props();

	let scrollableElement: HTMLElement;
	let onScrollCallbacks: (() => void)[] = [];

	let scrollableStore = writable<ScrollableStore>({
		getClientHeight: () => {
			return scrollableElement?.getBoundingClientRect().top + scrollableElement?.clientHeight;
		},
		onScroll: (callback: () => void) => {
			onScrollCallbacks.push(callback);
		}
	});

	function onscroll() {
		onScrollCallbacks?.forEach((cb) => cb());
	}

	setContext<ScrollableStore>('scrollable', $scrollableStore);
</script>

<div {...props} bind:this={scrollableElement} {onscroll}>
	{@render props.children?.()}
</div>
