// Frontend/skillforge-svelte/src/components/form/radio-field/RadioField.svelte
<script lang="ts">
	import type FormContext from "skillforge-common/types/FormContext";
	import { getContext, onMount } from "svelte";

    interface Props {
        id: string,
        name: string,
        label?: string,
        value: any,
        group: any,
        mod?: string,
        disabled?: boolean,
        isSwitch?: boolean,
        isInline?: boolean,
        isReverse?: boolean,
    }

    var {
        id,
        name,
        label = name,
        value,
        group = $bindable(),
        mod,
        disabled,
        isSwitch,
        isInline,
        isReverse,
    }: Props = $props();

    const formContext = getContext<FormContext>('form');

    export function reset() {
        group = formContext?.getFieldDefaultValue(name);
    }

    onMount(() => {
        formContext?.registerField(name, reset);
    })
</script>

<div class="form-check {mod}"
     class:form-switch={isSwitch}
     class:form-check-inline={isInline}
     class:form-check-reverse={isReverse}>
    <input {id}
            {name}
            {value}
            bind:group
            type="radio"
            class="form-check-input"
            {disabled}>
    <label for={id} class="form-check-label">{label}</label>
</div>

// Frontend/skillforge-react/src/components/form/radio-field/RadioField.tsx
import { useFormContext } from '@/context/FormContext';
import { FieldValues, RegisterOptions } from 'react-hook-form';

export interface IRadioFieldProps<T> {
    id: string;
    name: string;
    label?: string;
    value?: T;
    selectedOption: T;
    onChange?: (value: T) => void;
    options?: RegisterOptions<FieldValues, string> | undefined;
    classes?: string;
    disabled?: boolean;
    isSwitch?: boolean;
    isInline?: boolean;
    isReverse?: boolean;
}

export function RadioField<T extends string | number | readonly string[] | undefined>({
    id,
    name,
    label = name,
    value,
    selectedOption,
    onChange,
    options,
    classes = '',
    disabled,
    isSwitch,
    isInline,
    isReverse,
}: IRadioFieldProps<T>) {
    const formContext = useFormContext();

    return (
        <div className={`form-check ${classes} ${isSwitch ? 'form-switch' : ''} ${isInline ? 'form-check-inline' : ''} ${isReverse ? 'form-check-reverse' : ''}`}>
            <input id={id}
                {...formContext?.form.register(name, {
                    ...options,
                    onChange: event => onChange?.(event.target.value)
                })}
                value={value}
                checked={selectedOption == value}
                type="radio"
                className="form-check-input"
                disabled={disabled}
            />
            <label htmlFor={id} className="form-check-label">{label}</label>
        </div>
    );
}
