// Frontend/skillforge/src/components/form/TextAreaField.svelte
<script lang="ts">
	import type ValidatedField from '$lib/types/ValidatedField';
	import FieldValidation from './FieldValidation.svelte';
	import { getContext, onMount } from 'svelte';
	import type FormContext from '$lib/types/FormContext';

    interface Props {
        id: string,
        name?: string,
        label?: string,
        value: string | undefined | null,
        placeholder?: string,
        rows?: any,
        cols?: any,
        minlength?: any,
        maxlength?: any,
        mod?: string,
        disabled?: boolean,
        validateTogether?: string[],
    }

    var {
        id,
        name = id,
        label = name,
        value = $bindable(),
        placeholder,
        rows,
        cols,
        minlength,
        maxlength,
        mod,
        disabled,
        validateTogether,
    }: Props = $props();

    const formContext = getContext<FormContext>('form');

    let isValid = $state<boolean>(true);
    let isVisited = $state<boolean>(false);

    let fieldValidation: ValidatedField;
    function oninput() {
        fieldValidation?.validate();
    }

    function onfocus() {
        isVisited = true;
    }

    function onfocusout() {
        fieldValidation?.validate();
    }

    export function reset() {
        value = formContext?.getFieldDefaultValue(name);
    }

    onMount(() => {
        formContext?.registerField(name, reset);
    })
</script>

<div class="mb-4">
    <label for={id} class="form-label">{label}:</label>
    <textarea {id}
            {name}
            {placeholder}
            class="form-control {mod}"
            class:is-invalid={!isValid}
            bind:value
            {rows}
            {cols}
            {minlength}
            {maxlength}
            {oninput}
            {onfocus}
            {onfocusout}
            {disabled}></textarea>
    <FieldValidation {name} {label} {value} shouldValidate={isVisited} bind:isValid bind:this={fieldValidation} {validateTogether} />
</div>

// Frontend/skillforge-react/src/components/form/text-area-field/TextAreaField.tsx
import { useFormContext } from '@/context/FormContext';
import { FieldValues, RegisterOptions } from 'react-hook-form';

export interface ITextAreaFieldProps {
    id: string;
    name?: string;
    label?: string;
    value: string;
    onChange: (value: string) => void;
    options?: RegisterOptions<FieldValues, string> | undefined,
    placeholder?: string;
    rows?: any;
    cols?: any;
    minlength?: any;
    maxlength?: any;
    classes?: string;
    disabled?: boolean;
}

export function TextAreaField({
    id,
    name = id,
    label = name,
    value,
    onChange,
    options,
    placeholder,
    rows,
    cols,
    minlength,
    maxlength,
    classes = '',
    disabled,
}: ITextAreaFieldProps) {
    const formContext = useFormContext();
    const isInvalid = !!formContext?.form.formState.errors[name];

    return (
        <div className="mb-4">
            <label htmlFor={id} className="form-label">{label}:</label>
            <textarea id={id}
                {...formContext?.form.register(name, {
                    ...options,
                    onChange: event => onChange?.(event.target.value)
                })}
                placeholder={placeholder}
                className={`form-control ${classes} ${isInvalid ? 'is-invalid' : ''}`}
                value={value}
                rows={rows}
                cols={cols}
                minLength={minlength}
                maxLength={maxlength}
                disabled={disabled}></textarea>
            <div className="invalid-feedback">
                {isInvalid && formContext?.form.formState.errors[name]?.message as string}
            </div>
        </div>
    );
}
